import base64
import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend


class PortfolioContentExtractor:
    def __init__(self, html: str):
        self.html = html

    def extract(self) -> str:
        start_pattern = 'id="portfolio-content"'
        idx = self.html.find(start_pattern)
        if idx == -1:
            raise ValueError("Block #portfolio-content not found")
        tag_start = self.html.rfind("<div", 0, idx)
        if tag_start == -1:
            raise ValueError("Start tag not found")
        gt = self.html.find(">", tag_start)
        if gt == -1:
            raise ValueError("Tag not closed")
        pos = gt + 1
        depth = 1
        while pos < len(self.html) and depth > 0:
            next_open = self.html.find("<div", pos)
            next_close = self.html.find("</div>", pos)
            if next_close == -1:
                break
            if next_open != -1 and next_open < next_close:
                depth += 1
                pos = next_open + 4
            else:
                depth -= 1
                if depth == 0:
                    return self.html[gt + 1 : next_close]
                pos = next_close + 6
        raise ValueError("No matching closing tag")


def derive_key(password: bytes, salt: bytes) -> bytes:
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100_000,
        backend=default_backend(),
    )
    return kdf.derive(password)


def encrypt(password: str, plaintext: str) -> dict:
    salt = os.urandom(16)
    iv = os.urandom(12)
    key = derive_key(password.encode("utf-8"), salt)
    aesgcm = AESGCM(key)
    ciphertext = aesgcm.encrypt(iv, plaintext.encode("utf-8"), None)
    return {
        "ciphertext": base64.b64encode(ciphertext).decode("utf-8"),
        "iv": base64.b64encode(iv).decode("utf-8"),
        "salt": base64.b64encode(salt).decode("utf-8"),
    }


def main():
    if len(sys.argv) < 3:
        print("Usage: python encrypt_data.py <password> <output-base-dir>")
        sys.exit(1)

    password = sys.argv[1]
    base_dir = Path(sys.argv[2])
    pages = {
        "index": base_dir / "index.html",
        "anschreiben": base_dir / "anschreiben.html",
        "kurzprofil": base_dir / "kurzprofil.html",
        "lebenslauf": base_dir / "lebenslauf.html",
        "portfolio": base_dir / "portfolio.html",
    }

    output = base_dir / "assets" / "js" / "encrypted-data.js"
    output.parent.mkdir(parents=True, exist_ok=True)

    result = {}
    for key, path in pages.items():
        if not path.exists():
            print(f"Missing: {path}")
            sys.exit(1)
        html = path.read_text(encoding="utf-8")
        content = PortfolioContentExtractor(html).extract()
        encrypted = encrypt(password, content)
        result[key] = encrypted
        print(f"Encrypted {key}: {len(content)} chars -> {len(encrypted['ciphertext'])} base64 chars")

    js = "// AUTO-GENERATED ENCRYPTED DATA\n// DO NOT EDIT THIS FILE\nwindow.PORTFOLIO_DATA = " + json.dumps(result, indent=2) + ";\n"
    output.write_text(js, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
