import base64
import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend
from html.parser import HTMLParser


class InnerHTMLParser(HTMLParser):
    def __init__(self, target_id):
        super().__init__()
        self.target_id = target_id
        self.in_target = False
        self.depth = 0
        self.chunks = []

    def handle_starttag(self, tag, attrs):
        if not self.in_target:
            attr_dict = dict(attrs)
            if tag == "div" and attr_dict.get("id") == self.target_id:
                self.in_target = True
                self.depth = 1
                return
            return
        self.depth += 1
        self.chunks.append(self.get_starttag_text())

    def handle_endtag(self, tag):
        if not self.in_target:
            return
        if tag == "div":
            self.depth -= 1
            if self.depth == 0:
                self.in_target = False
                return
        self.chunks.append(f"</{tag}>")

    def handle_data(self, data):
        if self.in_target:
            self.chunks.append(data)

    def get_html(self):
        return "".join(self.chunks)


def derive_key(password: bytes, salt: bytes) -> bytes:
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100_000,
        backend=default_backend(),
    )
    return kdf.derive(password)


def encrypt(password: str, plaintext: str) -> dict:
    salt = os.urandom(16)
    iv = os.urandom(12)
    key = derive_key(password.encode("utf-8"), salt)
    aesgcm = AESGCM(key)
    ciphertext = aesgcm.encrypt(iv, plaintext.encode("utf-8"), None)
    return {
        "ciphertext": base64.b64encode(ciphertext).decode("utf-8"),
        "iv": base64.b64encode(iv).decode("utf-8"),
        "salt": base64.b64encode(salt).decode("utf-8"),
    }


def main():
    if len(sys.argv) < 3:
        print("Usage: python encrypt_data.py <password> <output-base-dir>")
        sys.exit(1)

    password = sys.argv[1]
    base_dir = Path(sys.argv[2])
    pages = {
        "index": base_dir / "index.html",
        "anschreiben": base_dir / "anschreiben.html",
        "kurzprofil": base_dir / "kurzprofil.html",
        "lebenslauf": base_dir / "lebenslauf.html",
        "portfolio": base_dir / "portfolio.html",
    }

    output = base_dir / "assets" / "js" / "encrypted-data.js"
    output.parent.mkdir(parents=True, exist_ok=True)

    result = {}
    for key, path in pages.items():
        if not path.exists():
            print(f"Missing: {path}")
            sys.exit(1)
        html = path.read_text(encoding="utf-8")
        parser = InnerHTMLParser("portfolio-content")
        parser.feed(html)
        content = parser.get_html()
        if not content.strip():
            print(f"WARNING: {key} content is empty after extraction")
        encrypted = encrypt(password, content)
        result[key] = encrypted
        print(f"Encrypted {key}: {len(content)} chars -> {len(encrypted['ciphertext'])} base64 chars")

    js = "// AUTO-GENERATED ENCRYPTED DATA\n// DO NOT EDIT THIS FILE\nwindow.PORTFOLIO_DATA = " + json.dumps(result, indent=2) + ";\n"
    output.write_text(js, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
